const { conversation,Simple } = require('@assistant/conversation');
const functions = require('firebase-functions');

const app = conversation();

function getRandomInt(min, max) {
  min = Math.ceil(min);
  max = Math.floor(max);
  return Math.floor(Math.random() * (max - min)) + min; //The maximum is exclusive and the minimum is inclusive
}
function get_day(d){
  let today = new Date();
  today.setHours(today.getHours() + 8);//サーバ時間を返すようなので、日本時間に変換
  today.setDate(today.getDate() + d);
  const month = today.getMonth() + 1;
  const day = today.getDate();
  return month + '月' + day + '日';
}
//本日の日付を返す
function get_today(){
  return get_day(0);
}
//明日の日付を返す
function get_tommorrow(){
  return get_day(1);
}

  const idols = {'アスラン=BBⅡ世': {'birthday': '10月9日',
               'kana': '',
               'label': 'アスラン=BBⅡ世',
               'pro': '315プロ',
               'pro_kana': 'さいこーぷろ'},
 'アナスタシア': {'birthday': '9月19日',
            'kana': 'あなすたしあ',
            'label': 'アナスタシア',
            'pro': '346プロ',
            'pro_kana': 'みしろぷろ'},
 'イヴ・サンタクロース': {'birthday': '12月24日',
                'kana': 'いゔ・さんたくろーす',
                'label': 'イヴ・サンタクロース',
                'pro': '346プロ',
                'pro_kana': 'みしろぷろ'},
 'エミリー': {'birthday': '1月8日',
          'kana': 'えみりーすちゅあーと',
          'label': 'エミリー',
          'pro': '765プロ',
          'pro_kana': 'なむこぷろ'},
 'キャシー・グラハム': {'birthday': '9月19日',
               'kana': 'きゃしー・ぐらはむ',
               'label': 'キャシー・グラハム',
               'pro': '346プロ',
               'pro_kana': 'みしろぷろ'},
 'クラリス': {'birthday': '8月26日',
          'kana': 'くらりす',
          'label': 'クラリス',
          'pro': '346プロ',
          'pro_kana': 'みしろぷろ'},
 'ケイト': {'birthday': '8月15日',
         'kana': 'けいと',
         'label': 'ケイト',
         'pro': '346プロ',
         'pro_kana': 'みしろぷろ'},
 'サイネリア': {'birthday': '12月14日',
           'kana': 'すずきあやね',
           'label': 'サイネリア',
           'pro': '876プロ',
           'pro_kana': 'ばんなむぷろ'},
 'ジュリア': {'birthday': '9月26日',
          'kana': '',
          'label': 'ジュリア',
          'pro': '765プロ',
          'pro_kana': 'なむこぷろ'},
 'ナターリア': {'birthday': '6月29日',
           'kana': 'なたーりあ',
           'label': 'ナターリア',
           'pro': '346プロ',
           'pro_kana': 'みしろぷろ'},
 'ピエール': {'birthday': '8月1日',
          'kana': 'ぴえーる',
          'label': 'ピエール',
          'pro': '315プロ',
          'pro_kana': 'さいこーぷろ'},
 'ヘレン': {'birthday': '4月4日',
         'kana': 'へれん',
         'label': 'ヘレン',
         'pro': '346プロ',
         'pro_kana': 'みしろぷろ'},
 'メアリー・コクラン': {'birthday': '1月19日',
               'kana': 'めありー・こくらん',
               'label': 'メアリー・コクラン',
               'pro': '346プロ',
               'pro_kana': 'みしろぷろ'},
 'ライラ': {'birthday': '5月21日',
         'kana': 'らいら',
         'label': 'ライラ',
         'pro': '346プロ',
         'pro_kana': 'みしろぷろ'},
 'ロコ': {'birthday': '3月1日',
        'kana': 'はんだろこ',
        'label': 'ロコ',
        'pro': '765プロ',
        'pro_kana': 'なむこぷろ'},
 '一ノ瀬志希': {'birthday': '5月30日',
           'kana': 'いちのせしき',
           'label': '一ノ瀬志希',
           'pro': '346プロ',
           'pro_kana': 'みしろぷろ'},
 '七尾百合子': {'birthday': '3月18日',
           'kana': 'ななおゆりこ',
           'label': '七尾百合子',
           'pro': '765プロ',
           'pro_kana': 'なむこぷろ'},
 '三好紗南': {'birthday': '6月25日',
          'kana': 'みよしさな',
          'label': '三好紗南',
          'pro': '346プロ',
          'pro_kana': 'みしろぷろ'},
 '三峰結華': {'birthday': '1月16日',
          'kana': 'みつみねゆいか',
          'label': '三峰結華',
          'pro': '283プロ',
          'pro_kana': 'つばさぷろ'},
 '三村かな子': {'birthday': '1月6日',
           'kana': 'みむらかなこ',
           'label': '三村かな子',
           'pro': '346プロ',
           'pro_kana': 'みしろぷろ'},
 '三浦あずさ': {'birthday': '7月19日',
           'kana': 'みうらあずさ',
           'label': '三浦あずさ',
           'pro': '765プロ',
           'pro_kana': 'なむこぷろ'},
 '三船美優': {'birthday': '2月25日',
          'kana': 'みふねみゆ',
          'label': '三船美優',
          'pro': '346プロ',
          'pro_kana': 'みしろぷろ'},
 '上条春菜': {'birthday': '4月10日',
          'kana': 'かみじょうはるな',
          'label': '上条春菜',
          'pro': '346プロ',
          'pro_kana': 'みしろぷろ'},
 '上田鈴帆': {'birthday': '10月26日',
          'kana': 'うえだすずほ',
          'label': '上田鈴帆',
          'pro': '346プロ',
          'pro_kana': 'みしろぷろ'},
 '並木芽衣子': {'birthday': '10月14日',
           'kana': 'なみきめいこ',
           'label': '並木芽衣子',
           'pro': '346プロ',
           'pro_kana': 'みしろぷろ'},
 '中谷育': {'birthday': '12月16日',
         'kana': 'なかたにいく',
         'label': '中谷育',
         'pro': '765プロ',
         'pro_kana': 'なむこぷろ'},
 '中野有香': {'birthday': '3月23日',
          'kana': 'なかのゆか',
          'label': '中野有香',
          'pro': '346プロ',
          'pro_kana': 'みしろぷろ'},
 '丹羽仁美': {'birthday': '6月4日',
          'kana': 'にわひとみ',
          'label': '丹羽仁美',
          'pro': '346プロ',
          'pro_kana': 'みしろぷろ'},
 '久川凪': {'birthday': '6月16日',
         'kana': 'ひさかわなぎ',
         'label': '久川凪',
         'pro': '346プロ',
         'pro_kana': 'みしろぷろ'},
 '久川颯': {'birthday': '6月16日',
         'kana': 'ひさかわはやて',
         'label': '久川颯',
         'pro': '346プロ',
         'pro_kana': 'みしろぷろ'},
 '乙倉悠貴': {'birthday': '10月6日',
          'kana': 'おとくらゆうき',
          'label': '乙倉悠貴',
          'pro': '346プロ',
          'pro_kana': 'みしろぷろ'},
 '九十九一希': {'birthday': '10月13日',
           'kana': 'つくもかずき',
           'label': '九十九一希',
           'pro': '315プロ',
           'pro_kana': 'さいこーぷろ'},
 '二宮飛鳥': {'birthday': '2月3日',
          'kana': 'にのみやあすか',
          'label': '二宮飛鳥',
          'pro': '346プロ',
          'pro_kana': 'みしろぷろ'},
 '二階堂千鶴': {'birthday': '10月21日',
           'kana': 'にかいどうちづる',
           'label': '二階堂千鶴',
           'pro': '765プロ',
           'pro_kana': 'なむこぷろ'},
 '五十嵐響子': {'birthday': '8月10日',
           'kana': 'いがらしきょうこ',
           'label': '五十嵐響子',
           'pro': '346プロ',
           'pro_kana': 'みしろぷろ'},
 '井村雪菜': {'birthday': '8月27日',
          'kana': 'いむらせつな',
          'label': '井村雪菜',
          'pro': '346プロ',
          'pro_kana': 'みしろぷろ'},
 '今井加奈': {'birthday': '3月3日',
          'kana': 'いまいかな',
          'label': '今井加奈',
          'pro': '346プロ',
          'pro_kana': 'みしろぷろ'},
 '仙崎恵磨': {'birthday': '6月27日',
          'kana': 'せんざきえま',
          'label': '仙崎恵磨',
          'pro': '346プロ',
          'pro_kana': 'みしろぷろ'},
 '伊吹翼': {'birthday': '7月30日',
         'kana': 'いぶきつばさ',
         'label': '伊吹翼',
         'pro': '765プロ',
         'pro_kana': 'なむこぷろ'},
 '伊瀬谷四季': {'birthday': '4月12日',
           'kana': 'いせやしき',
           'label': '伊瀬谷四季',
           'pro': '315プロ',
           'pro_kana': 'さいこーぷろ'},
 '伊集院北斗': {'birthday': '2月14日',
           'kana': 'いじゅういんほくと',
           'label': '伊集院北斗',
           'pro': '315プロ',
           'pro_kana': 'さいこーぷろ'},
 '伊集院惠': {'birthday': '9月24日',
          'kana': 'いじゅういんめぐみ',
          'label': '伊集院惠',
          'pro': '346プロ',
          'pro_kana': 'みしろぷろ'},
 '佐々木千枝': {'birthday': '6月7日',
           'kana': 'ささきちえ',
           'label': '佐々木千枝',
           'pro': '346プロ',
           'pro_kana': 'みしろぷろ'},
 '佐久間まゆ': {'birthday': '9月7日',
           'kana': 'さくままゆ',
           'label': '佐久間まゆ',
           'pro': '346プロ',
           'pro_kana': 'みしろぷろ'},
 '佐城雪美': {'birthday': '9月28日',
          'kana': 'さじょうゆきみ',
          'label': '佐城雪美',
          'pro': '346プロ',
          'pro_kana': 'みしろぷろ'},
 '佐竹美奈子': {'birthday': '3月22日',
           'kana': 'さたけみなこ',
           'label': '佐竹美奈子',
           'pro': '765プロ',
           'pro_kana': 'なむこぷろ'},
 '佐藤心': {'birthday': '7月22日',
         'kana': 'さとうしん',
         'label': '佐藤心',
         'pro': '346プロ',
         'pro_kana': 'みしろぷろ'},
 '依田芳乃': {'birthday': '7月3日',
          'kana': 'よりたよしの',
          'label': '依田芳乃',
          'pro': '346プロ',
          'pro_kana': 'みしろぷろ'},
 '信玄誠司': {'birthday': '12月24日',
          'kana': 'しんげんせいじ',
          'label': '信玄誠司',
          'pro': '315プロ',
          'pro_kana': 'さいこーぷろ'},
 '兜大吾': {'birthday': '5月20日',
         'kana': 'かぶとだいご',
         'label': '兜大吾',
         'pro': '315プロ',
         'pro_kana': 'さいこーぷろ'},
 '八宮めぐる': {'birthday': '7月22日',
           'kana': 'はちみやめぐる',
           'label': '八宮めぐる',
           'pro': '283プロ',
           'pro_kana': 'つばさぷろ'},
 '八神マキノ': {'birthday': '11月7日',
           'kana': 'やがみまきの',
           'label': '八神マキノ',
           'pro': '346プロ',
           'pro_kana': 'みしろぷろ'},
 '兵藤レナ': {'birthday': '10月3日',
          'kana': 'ひょうどうれな',
          'label': '兵藤レナ',
          'pro': '346プロ',
          'pro_kana': 'みしろぷろ'},
 '円城寺道流': {'birthday': '9月14日',
           'kana': 'えんじょうじみちる',
           'label': '円城寺道流',
           'pro': '315プロ',
           'pro_kana': 'さいこーぷろ'},
 '冬美旬': {'birthday': '1月2日',
         'kana': 'ふゆみじゅん',
         'label': '冬美旬',
         'pro': '315プロ',
         'pro_kana': 'さいこーぷろ'},
 '冴島清美': {'birthday': '9月26日',
          'kana': 'さえじまきよみ',
          'label': '冴島清美',
          'pro': '346プロ',
          'pro_kana': 'みしろぷろ'},
 '前川みく': {'birthday': '2月22日',
          'kana': 'まえかわみく',
          'label': '前川みく',
          'pro': '346プロ',
          'pro_kana': 'みしろぷろ'},
 '北上麗花': {'birthday': '5月17日',
          'kana': 'きたかみれいか',
          'label': '北上麗花',
          'pro': '765プロ',
          'pro_kana': 'なむこぷろ'},
 '北川真尋': {'birthday': '2月17日',
          'kana': 'きたがわまひろ',
          'label': '北川真尋',
          'pro': '346プロ',
          'pro_kana': 'みしろぷろ'},
 '北村想楽': {'birthday': '11月28日',
          'kana': 'きたむらそら',
          'label': '北村想楽',
          'pro': '315プロ',
          'pro_kana': 'さいこーぷろ'},
 '北条加蓮': {'birthday': '9月5日',
          'kana': 'ほうじょうかれん',
          'label': '北条加蓮',
          'pro': '346プロ',
          'pro_kana': 'みしろぷろ'},
 '北沢志保': {'birthday': '1月18日',
          'kana': 'きたざわしほ',
          'label': '北沢志保',
          'pro': '765プロ',
          'pro_kana': 'なむこぷろ'},
 '十時愛梨': {'birthday': '12月8日',
          'kana': 'とときあいり',
          'label': '十時愛梨',
          'pro': '346プロ',
          'pro_kana': 'みしろぷろ'},
 '南条光': {'birthday': '9月13日',
         'kana': 'なんじょうひかる',
         'label': '南条光',
         'pro': '346プロ',
         'pro_kana': 'みしろぷろ'},
 '卯月巻緒': {'birthday': '12月12日',
          'kana': 'うづきまきお',
          'label': '卯月巻緒',
          'pro': '315プロ',
          'pro_kana': 'さいこーぷろ'},
 '原田美世': {'birthday': '11月14日',
          'kana': 'はらだみよ',
          'label': '原田美世',
          'pro': '346プロ',
          'pro_kana': 'みしろぷろ'},
 '及川雫': {'birthday': '6月3日',
         'kana': 'おいかわしずく',
         'label': '及川雫',
         'pro': '346プロ',
         'pro_kana': 'みしろぷろ'},
 '双海亜美': {'birthday': '5月22日',
          'kana': 'ふたみあみ',
          'label': '双海亜美',
          'pro': '765プロ',
          'pro_kana': 'なむこぷろ'},
 '双海真美': {'birthday': '5月22日',
          'kana': 'ふたみまみ',
          'label': '双海真美',
          'pro': '765プロ',
          'pro_kana': 'なむこぷろ'},
 '双葉杏': {'birthday': '9月2日',
         'kana': 'ふたばあんず',
         'label': '双葉杏',
         'pro': '346プロ',
         'pro_kana': 'みしろぷろ'},
 '古澤頼子': {'birthday': '5月18日',
          'kana': 'ふるさわよりこ',
          'label': '古澤頼子',
          'pro': '346プロ',
          'pro_kana': 'みしろぷろ'},
 '古論クリス': {'birthday': '10月11日',
           'kana': 'ころんくりす',
           'label': '古論クリス',
           'pro': '315プロ',
           'pro_kana': 'さいこーぷろ'},
 '古賀小春': {'birthday': '4月1日',
          'kana': 'こがこはる',
          'label': '古賀小春',
          'pro': '346プロ',
          'pro_kana': 'みしろぷろ'},
 '吉岡沙紀': {'birthday': '5月8日',
          'kana': 'よしおかさき',
          'label': '吉岡沙紀',
          'pro': '346プロ',
          'pro_kana': 'みしろぷろ'},
 '向井拓海': {'birthday': '8月7日',
          'kana': 'むかいたくみ',
          'label': '向井拓海',
          'pro': '346プロ',
          'pro_kana': 'みしろぷろ'},
 '周防桃子': {'birthday': '11月6日',
          'kana': 'すおうももこ',
          'label': '周防桃子',
          'pro': '765プロ',
          'pro_kana': 'なむこぷろ'},
 '和久井留美': {'birthday': '4月7日',
           'kana': 'わくいるみ',
           'label': '和久井留美',
           'pro': '346プロ',
           'pro_kana': 'みしろぷろ'},
 '和泉愛依': {'birthday': '8月2日',
          'kana': 'いずみめい',
          'label': '和泉愛依',
          'pro': '283プロ',
          'pro_kana': 'つばさぷろ'},
 '喜多日菜子': {'birthday': '4月6日',
           'kana': 'きたひなこ',
           'label': '喜多日菜子',
           'pro': '346プロ',
           'pro_kana': 'みしろぷろ'},
 '喜多見柚': {'birthday': '12月2日',
          'kana': 'きたみゆず',
          'label': '喜多見柚',
          'pro': '346プロ',
          'pro_kana': 'みしろぷろ'},
 '四条貴音': {'birthday': '1月21日',
          'kana': 'しじょうたかね',
          'label': '四条貴音',
          'pro': '765プロ',
          'pro_kana': 'なむこぷろ'},
 '園田智代子': {'birthday': '2月24日',
           'kana': 'そのだちよこ',
           'label': '園田智代子',
           'pro': '283プロ',
           'pro_kana': 'つばさぷろ'},
 '土屋亜子': {'birthday': '5月2日',
          'kana': 'つちやあこ',
          'label': '土屋亜子',
          'pro': '346プロ',
          'pro_kana': 'みしろぷろ'},
 '城ヶ崎美嘉': {'birthday': '11月12日',
           'kana': 'じょうがさきみか',
           'label': '城ヶ崎美嘉',
           'pro': '346プロ',
           'pro_kana': 'みしろぷろ'},
 '城ヶ崎莉嘉': {'birthday': '7月30日',
           'kana': 'じょうがさきりか',
           'label': '城ヶ崎莉嘉',
           'pro': '346プロ',
           'pro_kana': 'みしろぷろ'},
 '堀裕子': {'birthday': '3月13日',
         'kana': 'ほりゆうこ',
         'label': '堀裕子',
         'pro': '346プロ',
         'pro_kana': 'みしろぷろ'},
 '塩見周子': {'birthday': '12月12日',
          'kana': 'しおみしゅうこ',
          'label': '塩見周子',
          'pro': '346プロ',
          'pro_kana': 'みしろぷろ'},
 '多田李衣菜': {'birthday': '6月30日',
           'kana': 'ただりいな',
           'label': '多田李衣菜',
           'pro': '346プロ',
           'pro_kana': 'みしろぷろ'},
 '夢見りあむ': {'birthday': '9月12日',
           'kana': 'ゆめみりあむ',
           'label': '夢見りあむ',
           'pro': '346プロ',
           'pro_kana': 'みしろぷろ'},
 '大原みちる': {'birthday': '4月12日',
           'kana': 'おおはらみちる',
           'label': '大原みちる',
           'pro': '346プロ',
           'pro_kana': 'みしろぷろ'},
 '大和亜季': {'birthday': '12月16日',
          'kana': 'やまとあき',
          'label': '大和亜季',
          'pro': '346プロ',
          'pro_kana': 'みしろぷろ'},
 '大崎甘奈': {'birthday': '12月25日',
          'kana': 'おおさきあまな',
          'label': '大崎甘奈',
          'pro': '283プロ',
          'pro_kana': 'つばさぷろ'},
 '大崎甜花': {'birthday': '12月25日',
          'kana': 'おおさきてんか',
          'label': '大崎甜花',
          'pro': '283プロ',
          'pro_kana': 'つばさぷろ'},
 '大槻唯': {'birthday': '5月7日',
         'kana': 'おおつきゆい',
         'label': '大槻唯',
         'pro': '346プロ',
         'pro_kana': 'みしろぷろ'},
 '大河タケル': {'birthday': '12月21日',
           'kana': 'たいがたける',
           'label': '大河タケル',
           'pro': '315プロ',
           'pro_kana': 'さいこーぷろ'},
 '大沼くるみ': {'birthday': '3月30日',
           'kana': 'おおぬまくるみ',
           'label': '大沼くるみ',
           'pro': '346プロ',
           'pro_kana': 'みしろぷろ'},
 '大石泉': {'birthday': '11月11日',
         'kana': 'おおいしいずみ',
         'label': '大石泉',
         'pro': '346プロ',
         'pro_kana': 'みしろぷろ'},
 '大神環': {'birthday': '4月29日',
         'kana': 'おおがみたまき',
         'label': '大神環',
         'pro': '765プロ',
         'pro_kana': 'なむこぷろ'},
 '大西由里子': {'birthday': '3月20日',
           'kana': 'おおにしゆりこ',
           'label': '大西由里子',
           'pro': '346プロ',
           'pro_kana': 'みしろぷろ'},
 '天ヶ瀬冬馬': {'birthday': '3月3日',
           'kana': 'あまがせとうま',
           'label': '天ヶ瀬冬馬',
           'pro': '315プロ',
           'pro_kana': 'さいこーぷろ'},
 '天海春香': {'birthday': '4月3日',
          'kana': 'あまみはるか',
          'label': '天海春香',
          'pro': '765プロ',
          'pro_kana': 'なむこぷろ'},
 '天空橋朋花': {'birthday': '11月11日',
           'kana': 'てんくうばしともか',
           'label': '天空橋朋花',
           'pro': '765プロ',
           'pro_kana': 'なむこぷろ'},
 '天道輝': {'birthday': '2月23日',
         'kana': 'てんどうてる',
         'label': '天道輝',
         'pro': '315プロ',
         'pro_kana': 'さいこーぷろ'},
 '太田優': {'birthday': '1月28日',
         'kana': 'おおたゆう',
         'label': '太田優',
         'pro': '346プロ',
         'pro_kana': 'みしろぷろ'},
 '奥山沙織': {'birthday': '6月12日',
          'kana': 'おくやまさおり',
          'label': '奥山沙織',
          'pro': '346プロ',
          'pro_kana': 'みしろぷろ'},
 '如月千早': {'birthday': '2月25日',
          'kana': 'きさらぎちはや',
          'label': '如月千早',
          'pro': '765プロ',
          'pro_kana': 'なむこぷろ'},
 '姫川友紀': {'birthday': '9月14日',
          'kana': 'ひめかわゆき',
          'label': '姫川友紀',
          'pro': '346プロ',
          'pro_kana': 'みしろぷろ'},
 '姫野かのん': {'birthday': '2月10日',
           'kana': 'ひめのかのん',
           'label': '姫野かのん',
           'pro': '315プロ',
           'pro_kana': 'さいこーぷろ'},
 '安斎都': {'birthday': '1月6日',
         'kana': 'あんざいみやこ',
         'label': '安斎都',
         'pro': '346プロ',
         'pro_kana': 'みしろぷろ'},
 '安部菜々': {'birthday': '5月15日',
          'kana': 'あべなな',
          'label': '安部菜々',
          'pro': '346プロ',
          'pro_kana': 'みしろぷろ'},
 '宮尾美也': {'birthday': '4月24日',
          'kana': 'みやおみや',
          'label': '宮尾美也',
          'pro': '765プロ',
          'pro_kana': 'なむこぷろ'},
 '宮本フレデリカ': {'birthday': '2月14日',
             'kana': 'みやもとふれでりか',
             'label': '宮本フレデリカ',
             'pro': '346プロ',
             'pro_kana': 'みしろぷろ'},
 '小室千奈美': {'birthday': '6月9日',
           'kana': 'こむろちなみ',
           'label': '小室千奈美',
           'pro': '346プロ',
           'pro_kana': 'みしろぷろ'},
 '小宮果穂': {'birthday': '7月29日',
          'kana': 'こみやかほ',
          'label': '小宮果穂',
          'pro': '283プロ',
          'pro_kana': 'つばさぷろ'},
 '小日向美穂': {'birthday': '12月16日',
           'kana': 'こひなたみほ',
           'label': '小日向美穂',
           'pro': '346プロ',
           'pro_kana': 'みしろぷろ'},
 '小早川紗枝': {'birthday': '10月18日',
           'kana': 'こばやかわさえ',
           'label': '小早川紗枝',
           'pro': '346プロ',
           'pro_kana': 'みしろぷろ'},
 '小松伊吹': {'birthday': '11月17日',
          'kana': 'こまついぶき',
          'label': '小松伊吹',
          'pro': '346プロ',
          'pro_kana': 'みしろぷろ'},
 '小関麗奈': {'birthday': '3月5日',
          'kana': 'こせきれいな',
          'label': '小関麗奈',
          'pro': '346プロ',
          'pro_kana': 'みしろぷろ'},
 '山下次郎': {'birthday': '9月1日',
          'kana': 'やましたじろう',
          'label': '山下次郎',
          'pro': '315プロ',
          'pro_kana': 'さいこーぷろ'},
 '岡崎泰葉': {'birthday': '7月16日',
          'kana': 'おかざきやすは',
          'label': '岡崎泰葉',
          'pro': '346プロ',
          'pro_kana': 'みしろぷろ'},
 '岡村直央': {'birthday': '3月25日',
          'kana': 'おかむらなお',
          'label': '岡村直央',
          'pro': '315プロ',
          'pro_kana': 'さいこーぷろ'},
 '岸部彩華': {'birthday': '11月13日',
          'kana': 'きしべあやか',
          'label': '岸部彩華',
          'pro': '346プロ',
          'pro_kana': 'みしろぷろ'},
 '島原エレナ': {'birthday': '10月26日',
           'kana': 'しまばらえれな',
           'label': '島原エレナ',
           'pro': '765プロ',
           'pro_kana': 'なむこぷろ'},
 '島村卯月': {'birthday': '4月24日',
          'kana': 'しまむらうづき',
          'label': '島村卯月',
          'pro': '346プロ',
          'pro_kana': 'みしろぷろ'},
 '川島瑞樹': {'birthday': '11月25日',
          'kana': 'かわしまみずき',
          'label': '川島瑞樹',
          'pro': '346プロ',
          'pro_kana': 'みしろぷろ'},
 '工藤忍': {'birthday': '3月9日',
         'kana': 'くどうしのぶ',
         'label': '工藤忍',
         'pro': '346プロ',
         'pro_kana': 'みしろぷろ'},
 '市原仁奈': {'birthday': '2月8日',
          'kana': 'いちはらにな',
          'label': '市原仁奈',
          'pro': '346プロ',
          'pro_kana': 'みしろぷろ'},
 '市川雛菜': {'birthday': '3月17日',
          'kana': 'いちかわひなな',
          'label': '市川雛菜',
          'pro': '283プロ',
          'pro_kana': 'つばさぷろ'},
 '幽谷霧子': {'birthday': '9月23日',
          'kana': 'ゆうこくきりこ',
          'label': '幽谷霧子',
          'pro': '283プロ',
          'pro_kana': 'つばさぷろ'},
 '御手洗翔太': {'birthday': '4月20日',
           'kana': 'みたらいしょうた',
           'label': '御手洗翔太',
           'pro': '315プロ',
           'pro_kana': 'さいこーぷろ'},
 '徳川まつり': {'birthday': '2月4日',
           'kana': 'とくがわまつり',
           'label': '徳川まつり',
           'pro': '765プロ',
           'pro_kana': 'なむこぷろ'},
 '愛野渚': {'birthday': '8月1日',
         'kana': 'あいのなぎさ',
         'label': '愛野渚',
         'pro': '346プロ',
         'pro_kana': 'みしろぷろ'},
 '成宮由愛': {'birthday': '11月3日',
          'kana': 'なるみやゆめ',
          'label': '成宮由愛',
          'pro': '346プロ',
          'pro_kana': 'みしろぷろ'},
 '我那覇響': {'birthday': '10月10日',
          'kana': 'がなはひびき',
          'label': '我那覇響',
          'pro': '765プロ',
          'pro_kana': 'なむこぷろ'},
 '所恵美': {'birthday': '4月15日',
         'kana': 'ところめぐみ',
         'label': '所恵美',
         'pro': '765プロ',
         'pro_kana': 'なむこぷろ'},
 '持田亜里沙': {'birthday': '8月24日',
           'kana': 'もちだありさ',
           'label': '持田亜里沙',
           'pro': '346プロ',
           'pro_kana': 'みしろぷろ'},
 '握野英雄': {'birthday': '3月7日',
          'kana': 'あくのひでお',
          'label': '握野英雄',
          'pro': '315プロ',
          'pro_kana': 'さいこーぷろ'},
 '斉藤洋子': {'birthday': '12月29日',
          'kana': 'さいとうようこ',
          'label': '斉藤洋子',
          'pro': '346プロ',
          'pro_kana': 'みしろぷろ'},
 '新田美波': {'birthday': '7月27日',
          'kana': 'にったみなみ',
          'label': '新田美波',
          'pro': '346プロ',
          'pro_kana': 'みしろぷろ'},
 '日下部若葉': {'birthday': '5月4日',
           'kana': 'くさかべわかば',
           'label': '日下部若葉',
           'pro': '346プロ',
           'pro_kana': 'みしろぷろ'},
 '日野茜': {'birthday': '8月4日',
         'kana': 'ひのあかね',
         'label': '日野茜',
         'pro': '346プロ',
         'pro_kana': 'みしろぷろ'},
 '日高愛': {'birthday': '6月25日',
         'kana': 'ひだかあい',
         'label': '日高愛',
         'pro': '876プロ',
         'pro_kana': 'ばんなむぷろ'},
 '早坂美玲': {'birthday': '5月9日',
          'kana': 'はやさかみれい',
          'label': '早坂美玲',
          'pro': '346プロ',
          'pro_kana': 'みしろぷろ'},
 '星井美希': {'birthday': '11月23日',
          'kana': 'ほしいみき',
          'label': '星井美希',
          'pro': '765プロ',
          'pro_kana': 'なむこぷろ'},
 '星輝子': {'birthday': '6月6日',
         'kana': 'ほししょうこ',
         'label': '星輝子',
         'pro': '346プロ',
         'pro_kana': 'みしろぷろ'},
 '春日未来': {'birthday': '6月28日',
          'kana': 'かすがみらい',
          'label': '春日未来',
          'pro': '765プロ',
          'pro_kana': 'なむこぷろ'},
 '最上静香': {'birthday': '9月14日',
          'kana': 'もがみしずか',
          'label': '最上静香',
          'pro': '765プロ',
          'pro_kana': 'なむこぷろ'},
 '月宮雅': {'birthday': '10月30日',
         'kana': 'つきみやみやび',
         'label': '月宮雅',
         'pro': '346プロ',
         'pro_kana': 'みしろぷろ'},
 '月岡恋鐘': {'birthday': '2月25日',
          'kana': 'つきおかこがね',
          'label': '月岡恋鐘',
          'pro': '283プロ',
          'pro_kana': 'つばさぷろ'},
 '有栖川夏葉': {'birthday': '8月16日',
           'kana': 'ありすがわなつは',
           'label': '有栖川夏葉',
           'pro': '283プロ',
           'pro_kana': 'つばさぷろ'},
 '有浦柑奈': {'birthday': '3月6日',
          'kana': 'ありうらかんな',
          'label': '有浦柑奈',
          'pro': '346プロ',
          'pro_kana': 'みしろぷろ'},
 '服部瞳子': {'birthday': '10月11日',
          'kana': 'はっとりとうこ',
          'label': '服部瞳子',
          'pro': '346プロ',
          'pro_kana': 'みしろぷろ'},
 '望月杏奈': {'birthday': '5月31日',
          'kana': 'もちづきあんな',
          'label': '望月杏奈',
          'pro': '765プロ',
          'pro_kana': 'なむこぷろ'},
 '望月聖': {'birthday': '12月25日',
         'kana': 'もちづきひじり',
         'label': '望月聖',
         'pro': '346プロ',
         'pro_kana': 'みしろぷろ'},
 '木下ひなた': {'birthday': '7月4日',
           'kana': 'きのしたひなた',
           'label': '木下ひなた',
           'pro': '765プロ',
           'pro_kana': 'なむこぷろ'},
 '木場真奈美': {'birthday': '8月8日',
           'kana': 'きばまなみ',
           'label': '木場真奈美',
           'pro': '346プロ',
           'pro_kana': 'みしろぷろ'},
 '木村夏樹': {'birthday': '8月19日',
          'kana': 'きむらなつき',
          'label': '木村夏樹',
          'pro': '346プロ',
          'pro_kana': 'みしろぷろ'},
 '木村龍': {'birthday': '5月5日',
         'kana': 'きむらりゅう',
         'label': '木村龍',
         'pro': '315プロ',
         'pro_kana': 'さいこーぷろ'},
 '本田未央': {'birthday': '12月1日',
          'kana': 'ほんだみお',
          'label': '本田未央',
          'pro': '346プロ',
          'pro_kana': 'みしろぷろ'},
 '杉坂海': {'birthday': '7月20日',
         'kana': 'すぎさかうみ',
         'label': '杉坂海',
         'pro': '346プロ',
         'pro_kana': 'みしろぷろ'},
 '村上巴': {'birthday': '1月3日',
         'kana': 'むらかみともえ',
         'label': '村上巴',
         'pro': '346プロ',
         'pro_kana': 'みしろぷろ'},
 '村松さくら': {'birthday': '3月27日',
           'kana': 'むらまつさくら',
           'label': '村松さくら',
           'pro': '346プロ',
           'pro_kana': 'みしろぷろ'},
 '杜野凛世': {'birthday': '10月19日',
          'kana': 'もりのりんぜ',
          'label': '杜野凛世',
          'pro': '283プロ',
          'pro_kana': 'つばさぷろ'},
 '東郷あい': {'birthday': '2月7日',
          'kana': 'とうごうあい',
          'label': '東郷あい',
          'pro': '346プロ',
          'pro_kana': 'みしろぷろ'},
 '東雲荘一郎': {'birthday': '11月8日',
           'kana': 'しののめそういちろう',
           'label': '東雲荘一郎',
           'pro': '315プロ',
           'pro_kana': 'さいこーぷろ'},
 '松原早耶': {'birthday': '12月28日',
          'kana': 'まつばらさや',
          'label': '松原早耶',
          'pro': '346プロ',
          'pro_kana': 'みしろぷろ'},
 '松尾千鶴': {'birthday': '3月21日',
          'kana': 'まつおちづる',
          'label': '松尾千鶴',
          'pro': '346プロ',
          'pro_kana': 'みしろぷろ'},
 '松山久美子': {'birthday': '1月21日',
           'kana': 'まつやまくみこ',
           'label': '松山久美子',
           'pro': '346プロ',
           'pro_kana': 'みしろぷろ'},
 '松本沙理奈': {'birthday': '9月1日',
           'kana': 'まつもとさりな',
           'label': '松本沙理奈',
           'pro': '346プロ',
           'pro_kana': 'みしろぷろ'},
 '松永涼': {'birthday': '10月1日',
         'kana': 'まつながりょう',
         'label': '松永涼',
         'pro': '346プロ',
         'pro_kana': 'みしろぷろ'},
 '松田亜利沙': {'birthday': '6月7日',
           'kana': 'まつだありさ',
           'label': '松田亜利沙',
           'pro': '765プロ',
           'pro_kana': 'なむこぷろ'},
 '柊志乃': {'birthday': '12月25日',
         'kana': 'ひいらぎしの',
         'label': '柊志乃',
         'pro': '346プロ',
         'pro_kana': 'みしろぷろ'},
 '柏木翼': {'birthday': '6月2日',
         'kana': 'かしわぎつばさ',
         'label': '柏木翼',
         'pro': '315プロ',
         'pro_kana': 'さいこーぷろ'},
 '柳清良': {'birthday': '5月12日',
         'kana': 'やなぎきよら',
         'label': '柳清良',
         'pro': '346プロ',
         'pro_kana': 'みしろぷろ'},
 '柳瀬美由紀': {'birthday': '3月16日',
           'kana': 'やなせみゆき',
           'label': '柳瀬美由紀',
           'pro': '346プロ',
           'pro_kana': 'みしろぷろ'},
 '栗原ネネ': {'birthday': '9月9日',
          'kana': 'くりはらねね',
          'label': '栗原ネネ',
          'pro': '346プロ',
          'pro_kana': 'みしろぷろ'},
 '桃井あずき': {'birthday': '7月7日',
           'kana': 'ももいあずき',
           'label': '桃井あずき',
           'pro': '346プロ',
           'pro_kana': 'みしろぷろ'},
 '桐生つかさ': {'birthday': '2月24日',
           'kana': 'きりゅうつかさ',
           'label': '桐生つかさ',
           'pro': '346プロ',
           'pro_kana': 'みしろぷろ'},
 '桐野アヤ': {'birthday': '4月8日',
          'kana': 'きりのあや',
          'label': '桐野アヤ',
          'pro': '346プロ',
          'pro_kana': 'みしろぷろ'},
 '桑山千雪': {'birthday': '4月18日',
          'kana': 'くわやまちゆき',
          'label': '桑山千雪',
          'pro': '283プロ',
          'pro_kana': 'つばさぷろ'},
 '桜井夢子': {'birthday': '10月24日',
          'kana': 'さくらいゆめこ',
          'label': '桜井夢子',
          'pro': '876プロ',
          'pro_kana': 'ばんなむぷろ'},
 '桜守歌織': {'birthday': '3月27日',
          'kana': 'さくらもりかおり',
          'label': '桜守歌織',
          'pro': '765プロ',
          'pro_kana': 'なむこぷろ'},
 '桜庭薫': {'birthday': '9月24日',
         'kana': 'さくらばかおる',
         'label': '桜庭薫',
         'pro': '315プロ',
         'pro_kana': 'さいこーぷろ'},
 '梅木音葉': {'birthday': '6月20日',
          'kana': 'うめきおとは',
          'label': '梅木音葉',
          'pro': '346プロ',
          'pro_kana': 'みしろぷろ'},
 '棟方愛海': {'birthday': '8月1日',
          'kana': 'むなかたあつみ',
          'label': '棟方愛海',
          'pro': '346プロ',
          'pro_kana': 'みしろぷろ'},
 '森久保乃々': {'birthday': '8月27日',
           'kana': 'もりくぼのの',
           'label': '森久保乃々',
           'pro': '346プロ',
           'pro_kana': 'みしろぷろ'},
 '椎名法子': {'birthday': '10月10日',
          'kana': 'しいなのりこ',
          'label': '椎名法子',
          'pro': '346プロ',
          'pro_kana': 'みしろぷろ'},
 '楊菲菲': {'birthday': '9月29日',
         'kana': 'やおふぇいふぇい',
         'label': '楊菲菲',
         'pro': '346プロ',
         'pro_kana': 'みしろぷろ'},
 '榊原里美': {'birthday': '8月27日',
          'kana': 'さかきばらさとみ',
          'label': '榊原里美',
          'pro': '346プロ',
          'pro_kana': 'みしろぷろ'},
 '榊夏来': {'birthday': '6月18日',
         'kana': 'さかきなつき',
         'label': '榊夏来',
         'pro': '315プロ',
         'pro_kana': 'さいこーぷろ'},
 '槙原志保': {'birthday': '4月27日',
          'kana': 'まきはらしほ',
          'label': '槙原志保',
          'pro': '346プロ',
          'pro_kana': 'みしろぷろ'},
 '樋口円香': {'birthday': '10月27日',
          'kana': 'ひぐちまどか',
          'label': '樋口円香',
          'pro': '283プロ',
          'pro_kana': 'つばさぷろ'},
 '横山千佳': {'birthday': '12月18日',
          'kana': 'よこやまちか',
          'label': '横山千佳',
          'pro': '346プロ',
          'pro_kana': 'みしろぷろ'},
 '横山奈緒': {'birthday': '2月12日',
          'kana': 'よこやまなお',
          'label': '横山奈緒',
          'pro': '765プロ',
          'pro_kana': 'なむこぷろ'},
 '橘ありす': {'birthday': '7月31日',
          'kana': 'たちばなありす',
          'label': '橘ありす',
          'pro': '346プロ',
          'pro_kana': 'みしろぷろ'},
 '橘志狼': {'birthday': '4月22日',
         'kana': 'たちばなしろう',
         'label': '橘志狼',
         'pro': '315プロ',
         'pro_kana': 'さいこーぷろ'},
 '櫻井桃華': {'birthday': '4月8日',
          'kana': 'さくらいももか',
          'label': '櫻井桃華',
          'pro': '346プロ',
          'pro_kana': 'みしろぷろ'},
 '櫻木真乃': {'birthday': '4月25日',
          'kana': 'さくらぎまの',
          'label': '櫻木真乃',
          'pro': '283プロ',
          'pro_kana': 'つばさぷろ'},
 '氏家むつみ': {'birthday': '7月13日',
           'kana': 'うじいえむつみ',
           'label': '氏家むつみ',
           'pro': '346プロ',
           'pro_kana': 'みしろぷろ'},
 '水嶋咲': {'birthday': '8月19日',
         'kana': 'みずしまさき',
         'label': '水嶋咲',
         'pro': '315プロ',
         'pro_kana': 'さいこーぷろ'},
 '水木聖來': {'birthday': '4月27日',
          'kana': 'みずきせいら',
          'label': '水木聖來',
          'pro': '346プロ',
          'pro_kana': 'みしろぷろ'},
 '水本ゆかり': {'birthday': '10月18日',
           'kana': 'みずもとゆかり',
           'label': '水本ゆかり',
           'pro': '346プロ',
           'pro_kana': 'みしろぷろ'},
 '水瀬伊織': {'birthday': '5月5日',
          'kana': 'みなせいおり',
          'label': '水瀬伊織',
          'pro': '765プロ',
          'pro_kana': 'なむこぷろ'},
 '水谷絵理': {'birthday': '3月7日',
          'kana': 'みずたにえり',
          'label': '水谷絵理',
          'pro': '876プロ',
          'pro_kana': 'ばんなむぷろ'},
 '水野翠': {'birthday': '12月5日',
         'kana': 'みずのみどり',
         'label': '水野翠',
         'pro': '346プロ',
         'pro_kana': 'みしろぷろ'},
 '永吉昴': {'birthday': '9月20日',
         'kana': 'ながよしすばる',
         'label': '永吉昴',
         'pro': '765プロ',
         'pro_kana': 'なむこぷろ'},
 '江上椿': {'birthday': '2月6日',
         'kana': 'えがみつばき',
         'label': '江上椿',
         'pro': '346プロ',
         'pro_kana': 'みしろぷろ'},
 '池袋晶葉': {'birthday': '6月10日',
          'kana': 'いけぶくろあきは',
          'label': '池袋晶葉',
          'pro': '346プロ',
          'pro_kana': 'みしろぷろ'},
 '沢田麻理菜': {'birthday': '5月6日',
           'kana': 'さわだまりな',
           'label': '沢田麻理菜',
           'pro': '346プロ',
           'pro_kana': 'みしろぷろ'},
 '浅倉透': {'birthday': '5月4日',
         'kana': 'あさくらとおる',
         'label': '浅倉透',
         'pro': '283プロ',
         'pro_kana': 'つばさぷろ'},
 '浅利七海': {'birthday': '10月9日',
          'kana': 'あさりななみ',
          'label': '浅利七海',
          'pro': '346プロ',
          'pro_kana': 'みしろぷろ'},
 '浅野風香': {'birthday': '2月11日',
          'kana': 'あさのふうか',
          'label': '浅野風香',
          'pro': '346プロ',
          'pro_kana': 'みしろぷろ'},
 '浜口あやめ': {'birthday': '1月13日',
           'kana': 'はまぐちあやめ',
           'label': '浜口あやめ',
           'pro': '346プロ',
           'pro_kana': 'みしろぷろ'},
 '浜川愛結奈': {'birthday': '5月25日',
           'kana': 'はまかわあゆな',
           'label': '浜川愛結奈',
           'pro': '346プロ',
           'pro_kana': 'みしろぷろ'},
 '海老原菜帆': {'birthday': '8月3日',
           'kana': 'えびはらなほ',
           'label': '海老原菜帆',
           'pro': '346プロ',
           'pro_kana': 'みしろぷろ'},
 '涼宮星花': {'birthday': '8月28日',
          'kana': 'すずみやせいか',
          'label': '涼宮星花',
          'pro': '346プロ',
          'pro_kana': 'みしろぷろ'},
 '清澄九郎': {'birthday': '7月3日',
          'kana': 'きよすみくろう',
          'label': '清澄九郎',
          'pro': '315プロ',
          'pro_kana': 'さいこーぷろ'},
 '渋谷凛': {'birthday': '8月10日',
         'kana': 'しぶやりん',
         'label': '渋谷凛',
         'pro': '346プロ',
         'pro_kana': 'みしろぷろ'},
 '渡辺みのり': {'birthday': '3月22日',
           'kana': 'わたなべみのり',
           'label': '渡辺みのり',
           'pro': '315プロ',
           'pro_kana': 'さいこーぷろ'},
 '瀬名詩織': {'birthday': '1月10日',
          'kana': 'せなしおり',
          'label': '瀬名詩織',
          'pro': '346プロ',
          'pro_kana': 'みしろぷろ'},
 '片桐早苗': {'birthday': '3月7日',
          'kana': 'かたぎりさなえ',
          'label': '片桐早苗',
          'pro': '346プロ',
          'pro_kana': 'みしろぷろ'},
 '牙崎漣': {'birthday': '5月14日',
         'kana': 'きざきれん',
         'label': '牙崎漣',
         'pro': '315プロ',
         'pro_kana': 'さいこーぷろ'},
 '猫柳キリオ': {'birthday': '11月12日',
           'kana': 'ねこやなぎきりお',
           'label': '猫柳キリオ',
           'pro': '315プロ',
           'pro_kana': 'さいこーぷろ'},
 '田中摩美々': {'birthday': '5月24日',
           'kana': 'たなかまみみ',
           'label': '田中摩美々',
           'pro': '283プロ',
           'pro_kana': 'つばさぷろ'},
 '田中琴葉': {'birthday': '10月5日',
          'kana': 'たなかことは',
          'label': '田中琴葉',
          'pro': '765プロ',
          'pro_kana': 'なむこぷろ'},
 '白坂小梅': {'birthday': '3月28日',
          'kana': 'しらさかこうめ',
          'label': '白坂小梅',
          'pro': '346プロ',
          'pro_kana': 'みしろぷろ'},
 '白瀬咲耶': {'birthday': '6月27日',
          'kana': 'しらせさくや',
          'label': '白瀬咲耶',
          'pro': '283プロ',
          'pro_kana': 'つばさぷろ'},
 '白石紬': {'birthday': '5月29日',
         'kana': 'しらいしつむぎ',
         'label': '白石紬',
         'pro': '765プロ',
         'pro_kana': 'なむこぷろ'},
 '白菊ほたる': {'birthday': '4月19日',
           'kana': 'しらぎくほたる',
           'label': '白菊ほたる',
           'pro': '346プロ',
           'pro_kana': 'みしろぷろ'},
 '白雪千夜': {'birthday': '2月4日',
          'kana': 'しらゆきちよ',
          'label': '白雪千夜',
          'pro': '346プロ',
          'pro_kana': 'みしろぷろ'},
 '百瀬莉緒': {'birthday': '11月21日',
          'kana': 'ももせりお',
          'label': '百瀬莉緒',
          'pro': '765プロ',
          'pro_kana': 'なむこぷろ'},
 '的場梨沙': {'birthday': '11月19日',
          'kana': 'まとばりさ',
          'label': '的場梨沙',
          'pro': '346プロ',
          'pro_kana': 'みしろぷろ'},
 '相原雪乃': {'birthday': '2月14日',
          'kana': 'あいはらゆきの',
          'label': '相原雪乃',
          'pro': '346プロ',
          'pro_kana': 'みしろぷろ'},
 '相川千夏': {'birthday': '11月11日',
          'kana': 'あいかわちなつ',
          'label': '相川千夏',
          'pro': '346プロ',
          'pro_kana': 'みしろぷろ'},
 '相葉夕美': {'birthday': '4月15日',
          'kana': 'あいばゆみ',
          'label': '相葉夕美',
          'pro': '346プロ',
          'pro_kana': 'みしろぷろ'},
 '相馬夏美': {'birthday': '7月23日',
          'kana': 'そうまなつみ',
          'label': '相馬夏美',
          'pro': '346プロ',
          'pro_kana': 'みしろぷろ'},
 '真壁瑞希': {'birthday': '1月27日',
          'kana': 'まかべみずき',
          'label': '真壁瑞希',
          'pro': '765プロ',
          'pro_kana': 'なむこぷろ'},
 '真鍋いつき': {'birthday': '12月29日',
           'kana': 'まなべいつき',
           'label': '真鍋いつき',
           'pro': '346プロ',
           'pro_kana': 'みしろぷろ'},
 '矢口美羽': {'birthday': '7月10日',
          'kana': 'やぐちみう',
          'label': '矢口美羽',
          'pro': '346プロ',
          'pro_kana': 'みしろぷろ'},
 '矢吹可奈': {'birthday': '8月18日',
          'kana': 'やぶきかな',
          'label': '矢吹可奈',
          'pro': '765プロ',
          'pro_kana': 'なむこぷろ'},
 '砂塚あきら': {'birthday': '10月7日',
           'kana': 'すなづかあきら',
           'label': '砂塚あきら',
           'pro': '346プロ',
           'pro_kana': 'みしろぷろ'},
 '硲道夫': {'birthday': '1月13日',
         'kana': 'はざまみちお',
         'label': '硲道夫',
         'pro': '315プロ',
         'pro_kana': 'さいこーぷろ'},
 '神崎蘭子': {'birthday': '4月8日',
          'kana': 'かんざきらんこ',
          'label': '神崎蘭子',
          'pro': '346プロ',
          'pro_kana': 'みしろぷろ'},
 '神楽麗': {'birthday': '6月17日',
         'kana': 'かぐられい',
         'label': '神楽麗',
         'pro': '315プロ',
         'pro_kana': 'さいこーぷろ'},
 '神谷奈緒': {'birthday': '9月16日',
          'kana': 'かみやなお',
          'label': '神谷奈緒',
          'pro': '346プロ',
          'pro_kana': 'みしろぷろ'},
 '神谷幸広': {'birthday': '1月17日',
          'kana': 'かみやゆきひろ',
          'label': '神谷幸広',
          'pro': '315プロ',
          'pro_kana': 'さいこーぷろ'},
 '福丸小糸': {'birthday': '11月11日',
          'kana': 'ふくまるこいと',
          'label': '福丸小糸',
          'pro': '283プロ',
          'pro_kana': 'つばさぷろ'},
 '福山舞': {'birthday': '1月21日',
         'kana': 'ふくやままい',
         'label': '福山舞',
         'pro': '346プロ',
         'pro_kana': 'みしろぷろ'},
 '福田のり子': {'birthday': '3月30日',
           'kana': 'ふくだのりこ',
           'label': '福田のり子',
           'pro': '765プロ',
           'pro_kana': 'なむこぷろ'},
 '秋山隼人': {'birthday': '11月22日',
          'kana': 'あきやまはやと',
          'label': '秋山隼人',
          'pro': '315プロ',
          'pro_kana': 'さいこーぷろ'},
 '秋月律子': {'birthday': '6月23日',
          'kana': 'あきづきりつこ',
          'label': '秋月律子',
          'pro': '765プロ',
          'pro_kana': 'なむこぷろ'},
 '秋月涼': {'birthday': '9月15日',
         'kana': 'あきづきりょう',
         'label': '秋月涼',
         'pro': '315プロ',
         'pro_kana': 'さいこーぷろ'},
 '箱崎星梨花': {'birthday': '2月20日',
           'kana': 'はこざきせりか',
           'label': '箱崎星梨花',
           'pro': '765プロ',
           'pro_kana': 'なむこぷろ'},
 '篠原礼': {'birthday': '11月22日',
         'kana': 'しのはられい',
         'label': '篠原礼',
         'pro': '346プロ',
         'pro_kana': 'みしろぷろ'},
 '篠宮可憐': {'birthday': '8月27日',
          'kana': 'しのみやかれん',
          'label': '篠宮可憐',
          'pro': '765プロ',
          'pro_kana': 'なむこぷろ'},
 '紅井朱雀': {'birthday': '4月4日',
          'kana': 'あかいすざく',
          'label': '紅井朱雀',
          'pro': '315プロ',
          'pro_kana': 'さいこーぷろ'},
 '結城晴': {'birthday': '7月17日',
         'kana': 'ゆうきはる',
         'label': '結城晴',
         'pro': '346プロ',
         'pro_kana': 'みしろぷろ'},
 '綾瀬穂乃香': {'birthday': '5月29日',
           'kana': 'あやせほのか',
           'label': '綾瀬穂乃香',
           'pro': '346プロ',
           'pro_kana': 'みしろぷろ'},
 '緒方智絵里': {'birthday': '6月11日',
           'kana': 'おがたちえり',
           'label': '緒方智絵里',
           'pro': '346プロ',
           'pro_kana': 'みしろぷろ'},
 '脇山珠美': {'birthday': '9月20日',
          'kana': 'わきやまたまみ',
          'label': '脇山珠美',
          'pro': '346プロ',
          'pro_kana': 'みしろぷろ'},
 '舞浜歩': {'birthday': '7月23日',
         'kana': 'まいはまあゆむ',
         'label': '舞浜歩',
         'pro': '765プロ',
         'pro_kana': 'なむこぷろ'},
 '舞田類': {'birthday': '8月8日',
         'kana': 'まいたるい',
         'label': '舞田類',
         'pro': '315プロ',
         'pro_kana': 'さいこーぷろ'},
 '芹沢あさひ': {'birthday': '1月4日',
           'kana': 'せりざわあさひ',
           'label': '芹沢あさひ',
           'pro': '283プロ',
           'pro_kana': 'つばさぷろ'},
 '若林智香': {'birthday': '8月30日',
          'kana': 'わかばやしともか',
          'label': '若林智香',
          'pro': '346プロ',
          'pro_kana': 'みしろぷろ'},
 '若里春名': {'birthday': '3月30日',
          'kana': 'わかざとはるな',
          'label': '若里春名',
          'pro': '315プロ',
          'pro_kana': 'さいこーぷろ'},
 '荒木比奈': {'birthday': '4月9日',
          'kana': 'あらきひな',
          'label': '荒木比奈',
          'pro': '346プロ',
          'pro_kana': 'みしろぷろ'},
 '菊地真': {'birthday': '8月29日',
         'kana': 'きくちまこと',
         'label': '菊地真',
         'pro': '765プロ',
         'pro_kana': 'なむこぷろ'},
 '華村翔真': {'birthday': '8月24日',
          'kana': 'はなむらしょうま',
          'label': '華村翔真',
          'pro': '315プロ',
          'pro_kana': 'さいこーぷろ'},
 '萩原雪歩': {'birthday': '12月24日',
          'kana': 'はぎわらゆきほ',
          'label': '萩原雪歩',
          'pro': '765プロ',
          'pro_kana': 'なむこぷろ'},
 '葛之葉雨彦': {'birthday': '10月31日',
           'kana': 'くずのはあめひこ',
           'label': '葛之葉雨彦',
           'pro': '315プロ',
           'pro_kana': 'さいこーぷろ'},
 '蒼井享介': {'birthday': '7月7日',
          'kana': 'あおいきょうすけ',
          'label': '蒼井享介',
          'pro': '315プロ',
          'pro_kana': 'さいこーぷろ'},
 '蒼井悠介': {'birthday': '7月7日',
          'kana': 'あおいゆうすけ',
          'label': '蒼井悠介',
          'pro': '315プロ',
          'pro_kana': 'さいこーぷろ'},
 '藤原肇': {'birthday': '6月15日',
         'kana': 'ふじわらはじめ',
         'label': '藤原肇',
         'pro': '346プロ',
         'pro_kana': 'みしろぷろ'},
 '藤居朋': {'birthday': '7月1日',
         'kana': 'ふじいとも',
         'label': '藤居朋',
         'pro': '346プロ',
         'pro_kana': 'みしろぷろ'},
 '藤本里奈': {'birthday': '10月14日',
          'kana': 'ふじもとりな',
          'label': '藤本里奈',
          'pro': '346プロ',
          'pro_kana': 'みしろぷろ'},
 '衛藤美紗希': {'birthday': '3月18日',
           'kana': 'えとうみさき',
           'label': '衛藤美紗希',
           'pro': '346プロ',
           'pro_kana': 'みしろぷろ'},
 '西園寺琴歌': {'birthday': '1月23日',
           'kana': 'さいおんじことか',
           'label': '西園寺琴歌',
           'pro': '346プロ',
           'pro_kana': 'みしろぷろ'},
 '西城樹里': {'birthday': '11月26日',
          'kana': 'さいじょうじゅり',
          'label': '西城樹里',
          'pro': '283プロ',
          'pro_kana': 'つばさぷろ'},
 '西島櫂': {'birthday': '8月17日',
         'kana': 'にしじまかい',
         'label': '西島櫂',
         'pro': '346プロ',
         'pro_kana': 'みしろぷろ'},
 '西川保奈美': {'birthday': '10月23日',
           'kana': 'にしかわほなみ',
           'label': '西川保奈美',
           'pro': '346プロ',
           'pro_kana': 'みしろぷろ'},
 '諸星きらり': {'birthday': '9月1日',
           'kana': 'もろぼしきらり',
           'label': '諸星きらり',
           'pro': '346プロ',
           'pro_kana': 'みしろぷろ'},
 '豊川風花': {'birthday': '9月2日',
          'kana': 'とよかわふうか',
          'label': '豊川風花',
          'pro': '765プロ',
          'pro_kana': 'なむこぷろ'},
 '財前時子': {'birthday': '4月18日',
          'kana': 'ざいぜんときこ',
          'label': '財前時子',
          'pro': '346プロ',
          'pro_kana': 'みしろぷろ'},
 '赤城みりあ': {'birthday': '4月14日',
           'kana': 'あかぎみりあ',
           'label': '赤城みりあ',
           'pro': '346プロ',
           'pro_kana': 'みしろぷろ'},
 '赤西瑛梨華': {'birthday': '7月7日',
           'kana': 'あかにしえりか',
           'label': '赤西瑛梨華',
           'pro': '346プロ',
           'pro_kana': 'みしろぷろ'},
 '輿水幸子': {'birthday': '11月25日',
          'kana': 'こしみずさちこ',
          'label': '輿水幸子',
          'pro': '346プロ',
          'pro_kana': 'みしろぷろ'},
 '辻野あかり': {'birthday': '11月5日',
           'kana': 'つじのあかり',
           'label': '辻野あかり',
           'pro': '346プロ',
           'pro_kana': 'みしろぷろ'},
 '速水奏': {'birthday': '7月1日',
         'kana': 'はやみかなで',
         'label': '速水奏',
         'pro': '346プロ',
         'pro_kana': 'みしろぷろ'},
 '遊佐こずえ': {'birthday': '2月19日',
           'kana': 'ゆさこずえ',
           'label': '遊佐こずえ',
           'pro': '346プロ',
           'pro_kana': 'みしろぷろ'},
 '道明寺歌鈴': {'birthday': '1月1日',
           'kana': 'どうみょうじかりん',
           'label': '道明寺歌鈴',
           'pro': '346プロ',
           'pro_kana': 'みしろぷろ'},
 '都築圭': {'birthday': '4月2日',
         'kana': 'つづきけい',
         'label': '都築圭',
         'pro': '315プロ',
         'pro_kana': 'さいこーぷろ'},
 '野々原茜': {'birthday': '12月3日',
          'kana': 'ののはらあかね',
          'label': '野々原茜',
          'pro': '765プロ',
          'pro_kana': 'なむこぷろ'},
 '野々村そら': {'birthday': '1月3日',
           'kana': 'ののむらそら',
           'label': '野々村そら',
           'pro': '346プロ',
           'pro_kana': 'みしろぷろ'},
 '長富蓮実': {'birthday': '3月19日',
          'kana': 'ながとみはすみ',
          'label': '長富蓮実',
          'pro': '346プロ',
          'pro_kana': 'みしろぷろ'},
 '間中美里': {'birthday': '11月6日',
          'kana': 'まなかみさと',
          'label': '間中美里',
          'pro': '346プロ',
          'pro_kana': 'みしろぷろ'},
 '関裕美': {'birthday': '8月17日',
         'kana': 'せきひろみ',
         'label': '関裕美',
         'pro': '346プロ',
         'pro_kana': 'みしろぷろ'},
 '難波笑美': {'birthday': '5月1日',
          'kana': 'なんばえみ',
          'label': '難波笑美',
          'pro': '346プロ',
          'pro_kana': 'みしろぷろ'},
 '風野灯織': {'birthday': '3月4日',
          'kana': 'かざのひおり',
          'label': '風野灯織',
          'pro': '283プロ',
          'pro_kana': 'つばさぷろ'},
 '首藤葵': {'birthday': '8月18日',
         'kana': 'しゅとうあおい',
         'label': '首藤葵',
         'pro': '346プロ',
         'pro_kana': 'みしろぷろ'},
 '馬場このみ': {'birthday': '6月12日',
           'kana': 'ばばこのみ',
           'label': '馬場このみ',
           'pro': '765プロ',
           'pro_kana': 'なむこぷろ'},
 '高坂海美': {'birthday': '8月10日',
          'kana': 'こうさかうみ',
          'label': '高坂海美',
          'pro': '765プロ',
          'pro_kana': 'なむこぷろ'},
 '高垣楓': {'birthday': '6月14日',
         'kana': 'たかがきかえで',
         'label': '高垣楓',
         'pro': '346プロ',
         'pro_kana': 'みしろぷろ'},
 '高山紗代子': {'birthday': '12月29日',
           'kana': 'たかやまさよこ',
           'label': '高山紗代子',
           'pro': '765プロ',
           'pro_kana': 'なむこぷろ'},
 '高峯のあ': {'birthday': '3月25日',
          'kana': 'たかみねのあ',
          'label': '高峯のあ',
          'pro': '346プロ',
          'pro_kana': 'みしろぷろ'},
 '高森藍子': {'birthday': '7月25日',
          'kana': 'たかもりあいこ',
          'label': '高森藍子',
          'pro': '346プロ',
          'pro_kana': 'みしろぷろ'},
 '高槻やよい': {'birthday': '3月25日',
           'kana': 'たかつきやよい',
           'label': '高槻やよい',
           'pro': '765プロ',
           'pro_kana': 'なむこぷろ'},
 '高橋礼子': {'birthday': '5月8日',
          'kana': 'たかはしれいこ',
          'label': '高橋礼子',
          'pro': '346プロ',
          'pro_kana': 'みしろぷろ'},
 '鷹城恭二': {'birthday': '2月2日',
          'kana': 'たかじょうきょうじ',
          'label': '鷹城恭二',
          'pro': '315プロ',
          'pro_kana': 'さいこーぷろ'},
 '鷹富士茄子': {'birthday': '1月1日',
           'kana': 'たかふじかこ',
           'label': '鷹富士茄子',
           'pro': '346プロ',
           'pro_kana': 'みしろぷろ'},
 '鷺沢文香': {'birthday': '10月27日',
          'kana': 'さぎさわふみか',
          'label': '鷺沢文香',
          'pro': '346プロ',
          'pro_kana': 'みしろぷろ'},
 '黒埼ちとせ': {'birthday': '11月10日',
           'kana': 'くろさきちとせ',
           'label': '黒埼ちとせ',
           'pro': '346プロ',
           'pro_kana': 'みしろぷろ'},
 '黒川千秋': {'birthday': '2月26日',
          'kana': 'くろかわちあき',
          'label': '黒川千秋',
          'pro': '346プロ',
          'pro_kana': 'みしろぷろ'},
 '黒野玄武': {'birthday': '7月22日',
          'kana': 'くろのげんぶ',
          'label': '黒野玄武',
          'pro': '315プロ',
          'pro_kana': 'さいこーぷろ'},
 '黛冬優子': {'birthday': '12月4日',
          'kana': 'まゆずみふゆこ',
          'label': '黛冬優子',
          'pro': '283プロ',
          'pro_kana': 'つばさぷろ'},
 '龍崎薫': {'birthday': '7月20日',
         'kana': 'りゅうざきかおる',
         'label': '龍崎薫',
         'pro': '346プロ',
         'pro_kana': 'みしろぷろ'}};

function get_prompt(date, label){
  let prompt = label + date + 'は';
  let speech = prompt;
  let count = 0;
  for (let name in idols){
    if (idols[name].birthday == date){    
      prompt += '、' + name + 'さん';
      if (idols[name].kana){
      	speech += '、' + idols[name].kana + 'さん';
      } else {
      	speech += '、' + name + ' さん';
      }

      count += 1;
    }
  }
  prompt += 'の誕生日です。';
  speech += 'の誕生日です。';
  if (count == 0){
    prompt = label + date + 'が誕生日のアイドルはいません。';
    speech = prompt;
  }
  return [prompt, speech];
}
app.handle('birthday', conv => {
  // Implement your code here
  
  const today = get_today();
  const [prompt_today, speech_today] = get_prompt(today, '今日');

  const tommorrow = get_tommorrow();
  const [prompt_tommorrow, speech_tommorrow] = get_prompt(tommorrow, '明日');

  //conv.add(prompt_today + '\n' + prompt_tommorrow);
  //「松永涼」は自然な発音になるが、「まつながりょう」は不自然な発音になる。
  //しかし「楊菲菲」は正しく読んでくれない。
  //speechとtextを別にするか悩む。
  conv.add(new Simple({
    speech: speech_today + '\n' + speech_tommorrow ,
    text: prompt_today + '\n' + prompt_tommorrow
  }));
  /*
  const date = new Date();
  conv.add(date.toString());  
  */
});

exports.ActionsOnGoogleFulfillment = functions.https.onRequest(app);
